### ISSUE TITLE
add option --color

### ISSUE THREAD

**Issue by glensc** [JakubOnderka/PHP-Parallel-Lint#78]
there exists `--no-color` option, but no opposite option `--color`.

the colorfulness seems to be auto detected, and the detection algorithm is unknown and it's apparently failing in ci environments where no real tty exists. would be nice to to force colors there.

**Comment by grogy** [comment]
It is great candidate for #Hacktoberfest.

@JakubOnderka you add label "Hacktoberfest", please?

**Comment by glady** [comment]
Nothing to do here for enabling colors. Colors are enabled by default and color-classes are set to force style. The problem seems to be within other project JakubOnderka/PHP-Console-Color within function \JakubOnderka\PhpConsoleColor\ConsoleColor::styleSequence. I made a pull request there (https://github.com/JakubOnderka/PHP-Console-Color/pull/10).

But here are more problems with that change. There is now really no further autodetection. On really not supported systems now the default creates a colored output. I will try to adapt that issue tomorrow.

**Comment by glady** [comment]
I should test first, before writing comments. I think the pull request #82 fixes this problem without changing ConsoleColor. I think there is no error, so i closed that other change.

**Comment by JakubOnderka** [comment]
Pull request #82 merged
